# Generated by Django 4.2.1 on 2023-06-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='internships',
            field=models.ManyToManyField(blank=True, null=True, to='internships.internship'),
        ),
    ]
