# Generated by Django 4.2.1 on 2023-06-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_alter_userinterest_internships'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternshipType',
            new_name='InternshipCategory',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='internship_type',
            new_name='internship_category',
        ),
    ]
