# Generated by Django 4.2.1 on 2023-06-03 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_rename_internshiptype_internshipcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='internships',
            field=models.ManyToManyField(blank=True, to='internships.internship'),
        ),
        migrations.AddField(
            model_name='internship',
            name='internship_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internships.internshiptype'),
        ),
    ]
