# Generated by Django 4.2.1 on 2023-06-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_internshiptype_alter_userinterest_internships_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='link',
            new_name='url',
        ),
    ]
