# Generated by Django 4.2.1 on 2023-06-04 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_rename_link_internship_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(100)]),
        ),
    ]
