# Generated by Django 4.2.1 on 2023-06-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0002_rename_loc_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
